In [2]:
import pandas as pd
import numpy as np

In [5]:
train_df = pd.read_csv("UNSW_NB15_training-set.csv")
test_df = pd.read_csv("UNSW_NB15_testing-set.csv")

In [11]:
print("Training Data rows: ",train_df.shape[0])
print("Training Data columns: ",train_df.shape[1])
print("Testing Data rows: ",test_df.shape[0])
print("Testing Data columns: ",test_df.shape[1])

Training Data rows:  175341
Training Data columns:  45
Testing Data rows:  82332
Testing Data columns:  45

In [12]:
train_df.head()

,id,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,...,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,attack_cat,label
0,1,0.121478,tcp,-,FIN,6,4,258,172,74.087490,...,1,1,0,0,0,1,1,0,Normal,0
1,2,0.649902,tcp,-,FIN,14,38,734,42014,78.473372,...,1,2,0,0,0,1,6,0,Normal,0
2,3,1.623129,tcp,-,FIN,8,16,364,13186,14.170161,...,1,3,0,0,0,2,6,0,Normal,0
3,4,1.681642,tcp,ftp,FIN,12,12,628,770,13.677108,...,1,3,1,1,0,2,1,0,Normal,0
4,5,0.449454,tcp,-,FIN,10,6,534,268,33.373826,...,1,40,0,0,0,2,39,0,Normal,0

In [184]:
test_df.columns.tolist()

['id',
 'dur',
 'proto',
 'service',
 'state',
 'spkts',
 'dpkts',
 'sbytes',
 'dbytes',
 'rate',
 'sttl',
 'dttl',
 'sload',
 'dload',
 'sloss',
 'dloss',
 'sinpkt',
 'dinpkt',
 'sjit',
 'djit',
 'swin',
 'stcpb',
 'dtcpb',
 'dwin',
 'tcprtt',
 'synack',
 'ackdat',
 'smean',
 'dmean',
 'trans_depth',
 'response_body_len',
 'ct_srv_src',
 'ct_state_ttl',
 'ct_dst_ltm',
 'ct_src_dport_ltm',
 'ct_dst_sport_ltm',
 'ct_dst_src_ltm',
 'is_ftp_login',
 'ct_ftp_cmd',
 'ct_flw_http_mthd',
 'ct_src_ltm',
 'ct_srv_dst',
 'is_sm_ips_ports',
 'attack_cat',
 'label']

# Keeping label and attack_cat as the target variable

In [19]:
train_df[['label', 'attack_cat']].tail(100)

        label attack_cat
175241      1    Generic
175242      1    Generic
175243      1    Generic
175244      1    Generic
175245      1    Generic
...       ...        ...
175336      1    Generic
175337      1  Shellcode
175338      1    Generic
175339      1    Generic
175340      1    Generic

[100 rows x 2 columns]

In [186]:
train_df['label'].value_counts()

label
1    119341
0     56000
Name: count, dtype: int64

In [21]:
train_df['attack_cat'].value_counts()

attack_cat
Normal            56000
Generic           40000
Exploits          33393
Fuzzers           18184
DoS               12264
Reconnaissance    10491
Analysis           2000
Backdoor           1746
Shellcode          1133
Worms               130
Name: count, dtype: int64

In [22]:
train_df.dtypes

id                     int64
dur                  float64
proto                    str
service                  str
state                    str
spkts                  int64
dpkts                  int64
sbytes                 int64
dbytes                 int64
rate                 float64
sttl                   int64
dttl                   int64
sload                float64
dload                float64
sloss                  int64
dloss                  int64
sinpkt               float64
dinpkt               float64
sjit                 float64
djit                 float64
swin                   int64
stcpb                  int64
dtcpb                  int64
dwin                   int64
tcprtt               float64
synack               float64
ackdat               float64
smean                  int64
dmean                  int64
trans_depth            int64
response_body_len      int64
ct_srv_src             int64
ct_state_ttl           int64
ct_dst_ltm             int64
ct_src_dport_ltm       int64
ct_dst_sport_ltm       int64
ct_dst_src_ltm         int64
is_ftp_login           int64
ct_ftp_cmd             int64
ct_flw_http_mthd       int64
ct_src_ltm             int64
ct_srv_dst             int64
is_sm_ips_ports        int64
attack_cat               str
label                  int64
dtype: object

In [31]:
train_df.select_dtypes(include=['string']).columns.tolist()

['proto', 'service', 'state', 'attack_cat']

In [32]:
train_df.columns = train_df.columns.str.strip().str.lower()

In [34]:
train_df.columns.tolist()

['id',
 'dur',
 'proto',
 'service',
 'state',
 'spkts',
 'dpkts',
 'sbytes',
 'dbytes',
 'rate',
 'sttl',
 'dttl',
 'sload',
 'dload',
 'sloss',
 'dloss',
 'sinpkt',
 'dinpkt',
 'sjit',
 'djit',
 'swin',
 'stcpb',
 'dtcpb',
 'dwin',
 'tcprtt',
 'synack',
 'ackdat',
 'smean',
 'dmean',
 'trans_depth',
 'response_body_len',
 'ct_srv_src',
 'ct_state_ttl',
 'ct_dst_ltm',
 'ct_src_dport_ltm',
 'ct_dst_sport_ltm',
 'ct_dst_src_ltm',
 'is_ftp_login',
 'ct_ftp_cmd',
 'ct_flw_http_mthd',
 'ct_src_ltm',
 'ct_srv_dst',
 'is_sm_ips_ports',
 'attack_cat',
 'label']

In [37]:
train_df.isnull().sum()

id                   0
dur                  0
proto                0
service              0
state                0
spkts                0
dpkts                0
sbytes               0
dbytes               0
rate                 0
sttl                 0
dttl                 0
sload                0
dload                0
sloss                0
dloss                0
sinpkt               0
dinpkt               0
sjit                 0
djit                 0
swin                 0
stcpb                0
dtcpb                0
dwin                 0
tcprtt               0
synack               0
ackdat               0
smean                0
dmean                0
trans_depth          0
response_body_len    0
ct_srv_src           0
ct_state_ttl         0
ct_dst_ltm           0
ct_src_dport_ltm     0
ct_dst_sport_ltm     0
ct_dst_src_ltm       0
is_ftp_login         0
ct_ftp_cmd           0
ct_flw_http_mthd     0
ct_src_ltm           0
ct_srv_dst           0
is_sm_ips_ports      0
attack_cat           0
label                0
dtype: int64

In [188]:
print("Train nulls:", train_df.isnull().sum().sum())

Train nulls: 0

In [40]:
print(test_df.isnull().sum().sum())

0

In [45]:
print("Train duplicates:", train_df.duplicated().sum())
print("Test duplicates:", test_df.duplicated().sum())

Train duplicates: 0
Test duplicates: 0

In [46]:
train_df['proto'].nunique()

133

In [49]:
train_df['service'].nunique()

13

In [51]:
train_df['state'].nunique()

9

In [52]:
train_df['attack_cat'].nunique()

10

In [53]:
train_df['proto'].unique()[:20]

<StringArray>
[      'tcp',       'udp',       'arp',      'ospf',      'icmp',      'igmp',
       'rtp',       'ddp', 'ipv6-frag',      'cftp',       'wsn',       'pvp',
  'wb-expak',       'mtp',   'pri-enc',   'sat-mon',      'cphb',    'sun-nd',
    'iso-ip',       'xtp']
Length: 20, dtype: str

In [54]:
train_df['service'].unique()

<StringArray>
[       '-',      'ftp',     'smtp',     'snmp',     'http', 'ftp-data',
      'dns',      'ssh',   'radius',     'pop3',     'dhcp',      'ssl',
      'irc']
Length: 13, dtype: str

In [55]:
train_df['state'].unique()

<StringArray>
['FIN', 'INT', 'CON', 'ECO', 'REQ', 'RST', 'PAR', 'URN', 'no']
Length: 9, dtype: str

In [56]:
train_df[['proto', 'service', 'state']].describe()

         proto service   state
count   175341  175341  175341
unique     133      13       9
top        tcp       -     INT
freq     79946   94168   82275

In [57]:
train_df.nunique()

id                   175341
dur                   74039
proto                   133
service                  13
state                     9
spkts                   480
dpkts                   443
sbytes                 7214
dbytes                 6660
rate                  76991
sttl                     11
dttl                      6
sload                 80885
dload                 77474
sloss                   409
dloss                   370
sinpkt                76161
dinpkt                74245
sjit                  77532
djit                  76831
swin                     13
stcpb                 75265
dtcpb                 75089
dwin                      7
tcprtt                43319
synack                40142
ackdat                37708
smean                  1357
dmean                  1328
trans_depth              11
response_body_len      2386
ct_srv_src               52
ct_state_ttl              5
ct_dst_ltm               50
ct_src_dport_ltm         47
ct_dst_sport_ltm         32
ct_dst_src_ltm           54
is_ftp_login              4
ct_ftp_cmd                4
ct_flw_http_mthd         11
ct_src_ltm               50
ct_srv_dst               52
is_sm_ips_ports           2
attack_cat               10
label                     2
dtype: int64

In [58]:
train_df[['is_ftp_login', 'ct_ftp_cmd', 'ct_flw_http_mthd', 'is_sm_ips_ports']].describe()

        is_ftp_login     ct_ftp_cmd  ct_flw_http_mthd  is_sm_ips_ports
count  175341.000000  175341.000000     175341.000000    175341.000000
mean        0.014948       0.014948          0.133066         0.015752
std         0.126048       0.126048          0.701208         0.124516
min         0.000000       0.000000          0.000000         0.000000
25%         0.000000       0.000000          0.000000         0.000000
50%         0.000000       0.000000          0.000000         0.000000
75%         0.000000       0.000000          0.000000         0.000000
max         4.000000       4.000000         30.000000         1.000000

In [64]:
train_df[['is_ftp_login', 'ct_ftp_cmd']].value_counts().head()

is_ftp_login  ct_ftp_cmd
0             0             172774
1             1               2545
4             4                 16
2             2                  6
Name: count, dtype: int64

In [65]:
(train_df['is_ftp_login'] == train_df['ct_ftp_cmd']).all()

np.True_

In [66]:
(train_df['is_ftp_login'] != train_df['ct_ftp_cmd']).sum()

np.int64(0)

In [67]:
(test_df['is_ftp_login'] == test_df['ct_ftp_cmd']).all()

np.False_

In [68]:
(test_df['is_ftp_login'] != test_df['ct_ftp_cmd']).sum()

np.int64(8)

In [69]:
test_df.loc[test_df['is_ftp_login'] != test_df['ct_ftp_cmd'], ['is_ftp_login', 'ct_ftp_cmd']].head(10)

       is_ftp_login  ct_ftp_cmd
28299             1           2
28305             1           2
29645             1           2
29656             1           2
32213             1           2
32259             1           2
37971             0           1
38838             0           1

In [70]:
train_df.columns.equals(test_df.columns)

True

In [71]:
test_df['label'].value_counts()

label
1    45332
0    37000
Name: count, dtype: int64

In [74]:
test_df['attack_cat'].value_counts()

attack_cat
Normal            37000
Generic           18871
Exploits          11132
Fuzzers            6062
DoS                4089
Reconnaissance     3496
Analysis            677
Backdoor            583
Shellcode           378
Worms                44
Name: count, dtype: int64

In [84]:
binary_feature_cols = train_df.columns.drop(['id', 'attack_cat', 'label'])
print(len(binary_feature_cols))

42

In [85]:
X_train_binary = train_df[binary_feature_cols]
X_test_binary = test_df[binary_feature_cols]

In [90]:
print("X train shape: ", X_train_binary.shape)
print("X test shape: ", X_test_binary.shape)

X train shape:  (175341, 42)
X test shape:  (82332, 42)

In [91]:
y_train_binary = train_df['label']
y_test_binary = test_df['label']

In [95]:
print(y_train_binary.count())
print(y_test_binary.count())

175341
82332

In [114]:
categorical = X_train_binary.select_dtypes(include = ['string']).columns.tolist()
numerical = X_train_binary.select_dtypes(exclude = ['string']).columns.tolist()

In [115]:
print("Categorical columns:", categorical)
print("Number of categorical columns:", len(categorical))
print("Number of numeric columns:", len(numerical))

Categorical columns: ['proto', 'service', 'state']
Number of categorical columns: 3
Number of numeric columns: 39

In [103]:
!pip install -U scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\rohan amir\appdata\local\programs\python\python314\lib\site-packages (from scikit-learn) (2.4.2)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp314-cp314-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.8.0-cp314-cp314-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.1 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.1 MB 2.0 MB/s eta 0:00:04
   ------- -------------------------------- 1.6/8.1 MB 3.7 MB/s eta 0:00:02
   --------------- ------------------------ 3.1/8.1 MB 4.9 MB/s eta 0:00:02
   ------------------------ --------------- 5.0/8.1 MB 5.8 MB/s eta 0:00:01
   --------------------------------- ------ 6.8/8.1 MB 6.4 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 6.6 MB/s  0:00:01
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.17.1-cp314-cp314-win_amd64.whl (37.3 MB)
   ---------------------------------------- 0.0/37.3 MB ? eta -:--:--
   -- ------------------------------------- 2.1/37.3 MB 10.1 MB/s eta 0:00:04
   ---- ----------------------------------- 4.2/37.3 MB 10.4 MB/s eta 0:00:04
   ------- -------------------------------- 6.6/37.3 MB 10.6 MB/s eta 0:00:03
   --------- ------------------------------ 8.9/37.3 MB 10.9 MB/s eta 0:00:03
   ------------ --------------------------- 11.5/37.3 MB 11.0 MB/s eta 0:00:03
   --------------- ------------------------ 14.2/37.3 MB 11.1 MB/s eta 0:00:03
   ---------------- ----------------------- 15.7/37.3 MB 11.2 MB/s eta 0:00:02
   ------------------- -------------------- 18.1/37.3 MB 10.7 MB/s eta 0:00:02
   ---------------------- ----------------- 20.7/37.3 MB 11.1 MB/s eta 0:00:02
   ----------------------- ---------------- 22.3/37.3 MB 10.6 MB/s eta 0:00:02
   ------------------------- -------------- 23.3/37.3 MB 10.3 MB/s eta 0:00:02
   -------------------------- ------------- 24.6/37.3 MB 9.8 MB/s eta 0:00:02
   --------------------------- ------------ 25.7/37.3 MB 9.5 MB/s eta 0:00:02
   ---------------------------- ----------- 27.0/37.3 MB 9.2 MB/s eta 0:00:02
   ------------------------------ --------- 28.3/37.3 MB 9.0 MB/s eta 0:00:02
   ------------------------------- -------- 29.4/37.3 MB 8.8 MB/s eta 0:00:01
   -------------------------------- ------- 30.7/37.3 MB 8.6 MB/s eta 0:00:01
   ---------------------------------- ----- 32.0/37.3 MB 8.5 MB/s eta 0:00:01
   ----------------------------------- ---- 33.3/37.3 MB 8.4 MB/s eta 0:00:01
   ------------------------------------- -- 34.6/37.3 MB 8.3 MB/s eta 0:00:01
   -------------------------------------- - 35.9/37.3 MB 8.2 MB/s eta 0:00:01
   ---------------------------------------  37.2/37.3 MB 8.1 MB/s eta 0:00:01
   ---------------------------------------- 37.3/37.3 MB 7.9 MB/s  0:00:04
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn

   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ---------------------------------------- 4/4 [scikit-learn]

Successfully installed joblib-1.5.3 scikit-learn-1.8.0 scipy-1.17.1 threadpoolctl-3.6.0

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [106]:
from sklearn.preprocessing import OneHotEncoder

In [107]:
ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [117]:
ohe.fit(X_train_binary[categorical])

OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [118]:
ohe.categories_

[array(['3pc', 'a/n', 'aes-sp3-d', 'any', 'argus', 'aris', 'arp', 'ax.25',
        'bbn-rcc', 'bna', 'br-sat-mon', 'cbt', 'cftp', 'chaos',
        'compaq-peer', 'cphb', 'cpnx', 'crtp', 'crudp', 'dcn', 'ddp',
        'ddx', 'dgp', 'egp', 'eigrp', 'emcon', 'encap', 'etherip', 'fc',
        'fire', 'ggp', 'gmtp', 'gre', 'hmp', 'i-nlsp', 'iatp', 'ib',
        'icmp', 'idpr', 'idpr-cmtp', 'idrp', 'ifmp', 'igmp', 'igp', 'il',
        'ip', 'ipcomp', 'ipcv', 'ipip', 'iplt', 'ipnip', 'ippc', 'ipv6',
        'ipv6-frag', 'ipv6-no', 'ipv6-opts', 'ipv6-route', 'ipx-n-ip',
        'irtp', 'isis', 'iso-ip', 'iso-tp4', 'kryptolan', 'l2tp', 'larp',
        'leaf-1', 'leaf-2', 'merit-inp', 'mfe-nsp', 'mhrp', 'micp',
        'mobile', 'mtp', 'mux', 'narp', 'netblt', 'nsfnet-igp', 'nvp',
        'ospf', 'pgm', 'pim', 'pipe', 'pnni', 'pri-enc', 'prm', 'ptp',
        'pup', 'pvp', 'qnx', 'rdp', 'rsvp', 'rtp', 'rvd', 'sat-expak',
        'sat-mon', 'sccopmce', 'scps', 'sctp', 'sdrp', 'secure-vmtp',
        'sep', 'skip', 'sm', 'smp', 'snp', 'sprite-rpc', 'sps', 'srp',
        'st2', 'stp', 'sun-nd', 'swipe', 'tcf', 'tcp', 'tlsp', 'tp++',
        'trunk-1', 'trunk-2', 'ttp', 'udp', 'unas', 'uti', 'vines', 'visa',
        'vmtp', 'vrrp', 'wb-expak', 'wb-mon', 'wsn', 'xnet', 'xns-idp',
        'xtp', 'zero'], dtype=object),
 array(['-', 'dhcp', 'dns', 'ftp', 'ftp-data', 'http', 'irc', 'pop3',
        'radius', 'smtp', 'snmp', 'ssh', 'ssl'], dtype=object),
 array(['CON', 'ECO', 'FIN', 'INT', 'PAR', 'REQ', 'RST', 'URN', 'no'],
       dtype=object)]

In [119]:
X_train_cat_encoded = ohe.transform(X_train_binary[categorical])

In [120]:
X_train_cat_encoded.shape

(175341, 155)

In [121]:
X_test_cat_encoded = ohe.transform(X_test_binary[categorical])

In [122]:
X_test_cat_encoded.shape

(82332, 155)

In [124]:
X_train_num = X_train_binary[numerical]
X_test_num = X_test_binary[numerical]

In [125]:
print(X_train_num.shape)
print(X_test_num.shape)

(175341, 39)
(82332, 39)

In [126]:
from sklearn.preprocessing import StandardScaler

In [127]:
scaler = StandardScaler()

In [128]:
scaler.fit(X_train_num)

StandardScaler()

In [129]:
scaler.mean_[:5]

array([1.35938869e+00, 2.02986637e+01, 1.89695907e+01, 8.84484384e+03,
       1.49289186e+04])

In [130]:
X_train_num_scaled = scaler.transform(X_train_num)

In [131]:
X_train_num_scaled.shape

(175341, 39)

In [132]:
X_test_num_scaled = scaler.transform(X_test_num)

In [133]:
X_test_num_scaled.shape

(82332, 39)

In [134]:
import numpy as np

X_train_processed = np.hstack((X_train_num_scaled, X_train_cat_encoded))
X_test_processed = np.hstack((X_test_num_scaled, X_test_cat_encoded))

In [135]:
print(X_train_processed.shape)
print(X_test_processed.shape)

(175341, 194)
(82332, 194)

# Preprocessing for stage 2 "Attack Type".

In [137]:
attack_train_df  = train_df[train_df['label'] == 1].copy()
attack_test_df = test_df[test_df['label'] == 1].copy()

In [138]:
print(attack_train_df.shape)
print(attack_test_df.shape)

(119341, 45)
(45332, 45)

In [139]:
attack_feature_cols = attack_train_df.columns.drop(['label', 'attack_cat', 'id'])

In [140]:
print(len(attack_feature_cols))
print(attack_feature_cols.tolist())

42
['dur', 'proto', 'service', 'state', 'spkts', 'dpkts', 'sbytes', 'dbytes', 'rate', 'sttl', 'dttl', 'sload', 'dload', 'sloss', 'dloss', 'sinpkt', 'dinpkt', 'sjit', 'djit', 'swin', 'stcpb', 'dtcpb', 'dwin', 'tcprtt', 'synack', 'ackdat', 'smean', 'dmean', 'trans_depth', 'response_body_len', 'ct_srv_src', 'ct_state_ttl', 'ct_dst_ltm', 'ct_src_dport_ltm', 'ct_dst_sport_ltm', 'ct_dst_src_ltm', 'is_ftp_login', 'ct_ftp_cmd', 'ct_flw_http_mthd', 'ct_src_ltm', 'ct_srv_dst', 'is_sm_ips_ports']

In [142]:
X_train_attack  = attack_train_df[attack_feature_cols]
X_test_attack = attack_test_df[attack_feature_cols]

y_train_attack = attack_train_df['attack_cat']
y_test_attack = attack_test_df['attack_cat']

In [144]:
print(X_train_attack.shape)
print(X_test_attack.shape)
print(y_train_attack.count())
print(y_test_attack.count())

(119341, 42)
(45332, 42)
119341
45332

In [147]:
attack_categorical_cols = X_train_attack.select_dtypes(include = ["string"]).columns.tolist()
attack_numeric_cols = X_train_attack.select_dtypes(exclude=['string']).columns.tolist()

In [148]:
print("Categorical:", attack_categorical_cols)
print("Number of categorical columns:", len(attack_categorical_cols))
print("Number of numeric columns:", len(attack_numeric_cols))

Categorical: ['proto', 'service', 'state']
Number of categorical columns: 3
Number of numeric columns: 39

In [149]:
from sklearn.preprocessing import OneHotEncoder
attack_ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [150]:
attack_ohe.fit(X_train_attack[attack_categorical_cols])

OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [151]:
attack_ohe.categories_

[array(['3pc', 'a/n', 'aes-sp3-d', 'any', 'argus', 'aris', 'ax.25',
        'bbn-rcc', 'bna', 'br-sat-mon', 'cbt', 'cftp', 'chaos',
        'compaq-peer', 'cphb', 'cpnx', 'crtp', 'crudp', 'dcn', 'ddp',
        'ddx', 'dgp', 'egp', 'eigrp', 'emcon', 'encap', 'etherip', 'fc',
        'fire', 'ggp', 'gmtp', 'gre', 'hmp', 'i-nlsp', 'iatp', 'ib',
        'idpr', 'idpr-cmtp', 'idrp', 'ifmp', 'igp', 'il', 'ip', 'ipcomp',
        'ipcv', 'ipip', 'iplt', 'ipnip', 'ippc', 'ipv6', 'ipv6-frag',
        'ipv6-no', 'ipv6-opts', 'ipv6-route', 'ipx-n-ip', 'irtp', 'isis',
        'iso-ip', 'iso-tp4', 'kryptolan', 'l2tp', 'larp', 'leaf-1',
        'leaf-2', 'merit-inp', 'mfe-nsp', 'mhrp', 'micp', 'mobile', 'mtp',
        'mux', 'narp', 'netblt', 'nsfnet-igp', 'nvp', 'ospf', 'pgm', 'pim',
        'pipe', 'pnni', 'pri-enc', 'prm', 'ptp', 'pup', 'pvp', 'qnx',
        'rdp', 'rsvp', 'rvd', 'sat-expak', 'sat-mon', 'sccopmce', 'scps',
        'sctp', 'sdrp', 'secure-vmtp', 'sep', 'skip', 'sm', 'smp', 'snp',
        'sprite-rpc', 'sps', 'srp', 'st2', 'stp', 'sun-nd', 'swipe', 'tcf',
        'tcp', 'tlsp', 'tp++', 'trunk-1', 'trunk-2', 'ttp', 'udp', 'unas',
        'uti', 'vines', 'visa', 'vmtp', 'vrrp', 'wb-expak', 'wb-mon',
        'wsn', 'xnet', 'xns-idp', 'xtp', 'zero'], dtype=object),
 array(['-', 'dhcp', 'dns', 'ftp', 'ftp-data', 'http', 'irc', 'pop3',
        'radius', 'smtp', 'snmp', 'ssh', 'ssl'], dtype=object),
 array(['CON', 'FIN', 'INT', 'REQ', 'RST'], dtype=object)]

In [152]:
X_train_attack_cat_encoded  = attack_ohe.transform(X_train_attack[attack_categorical_cols])
X_test_attack_cat_encoded = attack_ohe.transform(X_test_attack[attack_categorical_cols])

In [153]:
print(X_train_attack_cat_encoded.shape)
print(X_test_attack_cat_encoded.shape)

(119341, 147)
(45332, 147)

In [154]:
X_train_attack_num = X_train_attack[attack_numeric_cols]
X_test_attack_num = X_test_attack[attack_numeric_cols]

print(X_train_attack_num.shape)
print(X_test_attack_num.shape)

(119341, 39)
(45332, 39)

In [156]:
from sklearn.preprocessing import StandardScaler

In [159]:
attack_scaler = StandardScaler()

In [161]:
attack_scaler.fit(X_train_attack_num)

StandardScaler()

In [162]:
attack_scaler.mean_[:5]

array([1.51996932e+00, 1.54059460e+01, 1.00126193e+01, 1.10686554e+04,
       7.36445626e+03])

In [163]:
X_train_attack_num_scaled = attack_scaler.transform(X_train_attack_num)
X_test_attack_num_scaled = attack_scaler.transform(X_test_attack_num)

In [164]:
print(X_train_attack_num_scaled.shape)
print(X_test_attack_num_scaled.shape)

(119341, 39)
(45332, 39)

In [165]:
import numpy as np

X_train_attack_processed = np.hstack((X_train_attack_num_scaled, X_train_attack_cat_encoded))
X_test_attack_processed = np.hstack((X_test_attack_num_scaled, X_test_attack_cat_encoded))

In [166]:
print(X_train_attack_processed.shape)
print(X_test_attack_processed.shape)

(119341, 186)
(45332, 186)

In [167]:
from sklearn.preprocessing import LabelEncoder

In [168]:
attack_label_encoder = LabelEncoder()

In [169]:
attack_label_encoder.fit(y_train_attack)

LabelEncoder()

In [170]:
attack_label_encoder.classes_

array(['Analysis', 'Backdoor', 'DoS', 'Exploits', 'Fuzzers', 'Generic',
       'Reconnaissance', 'Shellcode', 'Worms'], dtype=object)

In [171]:
y_train_attack_encoded = attack_label_encoder.transform(y_train_attack)
y_test_attack_encoded = attack_label_encoder.transform(y_test_attack)

In [172]:
print(y_train_attack_encoded[:10])
print(y_test_attack_encoded[:10])

[1 1 1 1 1 1 1 1 1 1]
[6 6 1 2 3 0 3 3 3 3]

In [174]:
import numpy as np
import joblib
import os
# Save processed datasets
np.save("X_train_processed.npy", X_train_processed)
np.save("X_test_processed.npy", X_test_processed)

np.save("y_train_binary.npy", np.array(y_train_binary))
np.save("y_test_binary.npy", np.array(y_test_binary))

np.save("X_train_attack_processed.npy", X_train_attack_processed)
np.save("X_test_attack_processed.npy", X_test_attack_processed)

np.save("y_train_attack_encoded.npy", y_train_attack_encoded)
np.save("y_test_attack_encoded.npy", y_test_attack_encoded)

#Save preprocessors
joblib.dump(ohe, "binary_ohe.pkl")
joblib.dump(scaler, "binary_scaler.pkl")

joblib.dump(attack_ohe, "attack_ohe.pkl")
joblib.dump(attack_scaler, "attack_scaler.pkl")
joblib.dump(attack_label_encoder, "attack_label_encoder.pkl")

# Save column info
joblib.dump(binary_feature_cols.tolist(), "binary_feature_cols.pkl")
joblib.dump(categorical, "binary_categorical_cols.pkl")
joblib.dump(numerical, "binary_numeric_cols.pkl")

joblib.dump(attack_feature_cols.tolist(), "attack_feature_cols.pkl")
joblib.dump(attack_categorical_cols, "attack_categorical_cols.pkl")
joblib.dump(attack_numeric_cols, "attack_numeric_cols.pkl")

#Show saved files
print("Saved files:")
for file in sorted(os.listdir()):
    if file.endswith(".npy") or file.endswith(".pkl"):
        print(file)

Saved files:
X_test_attack_processed.npy
X_test_processed.npy
X_train_attack_processed.npy
X_train_processed.npy
attack_categorical_cols.pkl
attack_feature_cols.pkl
attack_label_encoder.pkl
attack_numeric_cols.pkl
attack_ohe.pkl
attack_scaler.pkl
binary_categorical_cols.pkl
binary_feature_cols.pkl
binary_numeric_cols.pkl
binary_ohe.pkl
binary_scaler.pkl
y_test_attack_encoded.npy
y_test_binary.npy
y_train_attack_encoded.npy
y_train_binary.npy